# CRIE UM PACOTE CHAMADO UTILIDADESCEV QUE TENHA DOIS pacotes INTERNOS CHAMDADOS MOEDA E DADO. TRANSFIRA TODAS AS
# FUNÇÕES UTILIZADAS NOS DESAFIOS 107, 108 E 109 PARA O PRIMEIRO PACOTE E MANTENHA TUDO FUNCIONANDO.

from UtilidadesCeV import moeda

p = float(input('Digite um preço: R$ '))
moeda.resumo(p,20,12)