# DENTRO DO PACOTE UTILIZADESCEV QUE CRIAMOS NO DESAFIO 111, TEMOS UM MÓDULO CHAMADO DADO, CRIE UMA FUNÇÃO CHAMADA
# LEIADINHEIRO() QUE SEJA CAPAZ DE FUNCIONAR COMO A FUNÇÃO INPUT(), MAS COM UMA VALIDAÇÃO DE DADOS PARA ACEITAR APENAS
# VALORES QUE SEJAM MONETÁRIOS.

from ex111.UtilidadesCeV import dado,moeda

preço=dado.leiadinheiro('Digite um preço: R$ ')
moeda.resumo(preço, 30, 15)